NumPy program to convert a list of numeric value into a one-dimensional NumPy array. 

In [11]:
import numpy as np
a = list(map(int, input("Enter multiple values to add to a list::\n").split()))

print("\nEntered list of numbers:: ", a)

count = 0
for i in range(len(a)):
    count = count + 1
    

array = np.array(a)
print("\nTotal number of elements:: ", count)
print("\nFinal array containing elements of list: \n", array)




Enter multiple values to add to a list::
 1 2 3 4 5 6



Entered list of numbers::  [1, 2, 3, 4, 5, 6]

Total number of elements::  6

Final array containing elements of list: 
 [1 2 3 4 5 6]


NumPy program to create a 3x3 matrix with values ranging from 2 to 10

In [12]:
import numpy as np

a = np.arange(2,11).reshape(3,3)
print("\nFinal 3x3 matrix::\n", a)


Final 3x3 matrix::
 [[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


NumPy program to reverse an array (first element becomes last).

In [17]:
import numpy as np

a = np.array([1,2,3,4,5])
print("Original Array::\n", a)

print("\n Reverse array with same elements: ")
a = a[::-1]
print(a)





Original Array::
 [1 2 3 4 5]

 Reverse array with same elements: 
[5 4 3 2 1]


NumPy program to create a null vector of size 10 and update sixth value to 11

In [18]:
import numpy as np

a = np.zeros(10)
print("\nOriginal Matrix::\n", a)

a[6] = 11

print("\nUpdated Matrix:\n", a)


Original Matrix::
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]

Updated Matrix:
 [ 0.  0.  0.  0.  0.  0. 11.  0.  0.  0.]


NumPy program to create a 2d array with 1 on the border and 0 inside.

In [31]:
a = np.ones((5,5))

print("\nOriginal Matrix\n", a)

a[1:-1, 1:-1] = 0
print("\nNew matrix:\n",a)


Original Matrix
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

New matrix:
 [[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


NumPy program to create an empty and a full array

In [32]:
a = np.empty((3,4))
print("\nEmpty Array::\n", a)

a = np.full((3,3),6)
print("\nFull Array::\n", a)



Empty Array::
 [[1.10416871e-311 3.16202013e-322 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 5.19555684e+170 3.26818789e-032 7.16706195e-038]
 [5.70093234e-038 3.44813210e-032 5.99271630e-038 4.01657082e-057]]

Full Array::
 [[6 6 6]
 [6 6 6]
 [6 6 6]]


NumPy program to append values to the end of an array

In [41]:
a = np.array([1,2,3,4,5])
print("\nOriginal Matrix:: \n", a)

b = np.append(a, [[1,2,3],[4,5,6]])
print("\nNew matrix after adding values:\n", b)



Original Matrix:: 
 [1 2 3 4 5]

New matrix after adding values:
 [1 2 3 4 5 1 2 3 4 5 6]


NumPy program to convert a list and tuple into arrays

In [46]:
## taking multiple inputs and saving it in a list

a = list(map(int, input("Enter multple values with spaces to save it in a list:").split()))
print("\nEntered list is :: ", a)

b = np.array(a)
print("Same values in a matrix:: ", b)

## taking multiple inputs and saving it in a tuple 

tup = tuple(map(int, input("\nEnter multple values with spaces to save it in a tuple:").split()))
print("\nEntered elements in a tuple: ", tup)

array = np.array(tup)
print("\nElements in a array: ", array)



Enter multple values with spaces to save it in a list: 1 2 3 4 5 



Entered list is ::  [1, 2, 3, 4, 5]
Same values in a matrix::  [1 2 3 4 5]



Enter multple values with spaces to save it in a tuple: 1 2 3 4 5



Entered elements in a tuple:  (1, 2, 3, 4, 5)

Elements in a array:  [1 2 3 4 5]
